# Default values for fellowship Test Environment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# when it's true ingress combines vue and vue application together
working_branches:
  enabled : false
workload_affinity:
  enabled: false
nameOverride: "conversations-ui"

replicaCount: 1

image:
  repository: 795540767663.dkr.ecr.eu-west-3.amazonaws.com/dev-conversations-ui
  tag: stable
  pullPolicy: IfNotPresent

nodeSelector: {}
tolerations: []
affinity: {}

resources:
  requests:
    memory: "100Mi"
    cpu: "100m"
  limits:
    memory: "200Mi"
    cpu: "200m"

#Affinity
workload_affinity:
    enabled: true
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: role
              operator: In
              values:
              - microservices