# Default values for fellowship Test Environment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# when it's true ingress combines laravel and vue application together
working_branch: false

nameOverride: "conversations-api"
app_name: conversations-api

replicaCount: 1

image:
  repository: 795540767663.dkr.ecr.eu-west-3.amazonaws.com/dev-conversations-api
  tag: stable
  pullPolicy: IfNotPresent

nodeSelector: {}
tolerations: []
affinity: {}

resources:
  enabled: true
  values:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "200Mi"
      cpu: "200m"

# Affinity
workload_affinity:
    enabled: true
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: role
              operator: In
              values:
              - microservices