apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  replicas: {{ .Values.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
{{- if .Values.workload_affinity.enabled -}}
{{- with .Values.workload_affinity.affinity }}
      affinity:
{{ toYaml . | indent 7 }}
{{- end }}
{{- end }}
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          name: {{ .Release.Name }}
          ports:
            - containerPort: 80
{{- with .Values.resources }}
          resources:
{{ toYaml . | indent 12 }}
{{- end }}